#!/usr/bin/env sh

while read file
do
  case "$1" in
    "C-d") mv "$file" ~/.trash ;;
    "C-c") echo -n "$file" | xclip -selection clipboard ;;
    "C-w") cp "$file" ~/.config/sway/wallpaper ;;
  esac
done

